[build]
  base = "Curriculum-FrontEnd-Angular-ES"
  publish = "Curriculum-FrontEnd-Angular-ES/dist/CV-CarlosTafur"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--openssl-legacy-provider"
